"""PR Babysitter Loop L2 implementation — review comment handling, isolated worktree fixes, upstream revalidation (V6-1103)."""

import logging
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from localforge.services.eval_corpus import LabeledEvent

logger = logging.getLogger(__name__)


class PRBabysitterAction(BaseModel):
    """Action outcome generated by PR Babysitter L2 (V6-1103)."""

    pr_id: int
    event_id: str
    action_type: str  # SMALL_FIX_WORKTREE, ESCALATE_CONFLICT, NOTIFY_HUMAN, REVALIDATE_UPSTREAM, IGNORE_DUPLICATE
    target_file: str | None = None
    target_line: int | None = None
    deduplicated: bool = False
    revalidated_upstream: bool = False
    evidence_invalidated: bool = False
    approved_self_pr: bool = False  # Strictly MUST be False
    merged_self_pr: bool = False    # Strictly MUST be False
    summary: str


class PRBabysitterLoopService:
    """Service managing L2 PR Babysitter — comment deduplication, small fixes, conflict escalation."""

    def __init__(self) -> None:
        self.processed_event_ids: set[str] = set()

    def process_pr_event(
        self, event: LabeledEvent, upstream_changed: bool = False
    ) -> PRBabysitterAction:
        """Process PR review comments or merge conflict events (V6-1103).

        Enforces:
        - Event deduplication (returns IGNORE_DUPLICATE if seen before).
        - Upstream branch change detection (invalidates stale evidence and revalidates).
        - Small fixes applied only in isolated worktree with exact file/line mapping.
        - Merge conflicts escalated to human notification (no silent overwrite).
        - Strict prohibition of self-approval or self-merge (approved_self_pr=False, merged_self_pr=False).
        """
        payload = event.payload
        pr_id = payload.get("pr_id", 0)

        # 1. Deduplication check (V6-1103 regression)
        if event.id in self.processed_event_ids:
            return PRBabysitterAction(
                pr_id=pr_id,
                event_id=event.id,
                action_type="IGNORE_DUPLICATE",
                deduplicated=True,
                approved_self_pr=False,
                merged_self_pr=False,
                summary=f"Event {event.id} already processed — duplicate ignored.",
            )

        self.processed_event_ids.add(event.id)

        # 2. Upstream branch change check
        evidence_invalidated = False
        if upstream_changed:
            logger.info("Upstream branch change detected for PR %d — invalidating stale evidence.", pr_id)
            evidence_invalidated = True

        # 3. Handle Merge Conflicts
        if event.category == "PR_MERGE_CONFLICT":
            return PRBabysitterAction(
                pr_id=pr_id,
                event_id=event.id,
                action_type="ESCALATE_CONFLICT",
                target_file=payload.get("conflicting_files", [None])[0],
                deduplicated=False,
                revalidated_upstream=upstream_changed,
                evidence_invalidated=evidence_invalidated,
                approved_self_pr=False,
                merged_self_pr=False,
                summary=f"Merge conflict in PR #{pr_id} escalated to human review. Silent overwrite prohibited.",
            )

        # 4. Handle Review Comment Small Fixes
        if event.category == "PR_REVIEW_COMMENT":
            target_file = payload.get("file_path")
            target_line = payload.get("line_number")
            return PRBabysitterAction(
                pr_id=pr_id,
                event_id=event.id,
                action_type="SMALL_FIX_WORKTREE",
                target_file=target_file,
                target_line=target_line,
                deduplicated=False,
                revalidated_upstream=upstream_changed,
                evidence_invalidated=evidence_invalidated,
                approved_self_pr=False,
                merged_self_pr=False,
                summary=f"Small fix applied in isolated worktree for PR #{pr_id} at {target_file}:{target_line}.",
            )

        return PRBabysitterAction(
            pr_id=pr_id,
            event_id=event.id,
            action_type="NOTIFY_HUMAN",
            deduplicated=False,
            revalidated_upstream=upstream_changed,
            evidence_invalidated=evidence_invalidated,
            approved_self_pr=False,
            merged_self_pr=False,
            summary=f"PR #{pr_id} event processed for human notification.",
        )
