apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forgeos-cloud.fullname" . }}-redis
  labels:
    {{- include "forgeos-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "forgeos-cloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "forgeos-cloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "redis:7-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgeos-cloud.fullname" . }}-redis
  labels:
    {{- include "forgeos-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "forgeos-cloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
