{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "forgeos-cloud.fullname" . }}-backend-hpa
  labels:
    app.kubernetes.io/component: backend-hpa
  annotations:
    forgeos.io/metrics-api-group: metrics.k8s.io
    forgeos.io/metrics-api-path: {{ .Values.autoscaling.metricsApiPath | quote }}
    forgeos.io/metrics-server-required: {{ .Values.autoscaling.metricsServerRequired | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "forgeos-cloud.fullname" . }}-backend
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
